export const MODE_INITIAL_TABLE_VIEW = 'MODE_INITIAL_TABLE_VIEW';
export const MODE_COSTUME_EDITOR = 'MODE_COSTUME_EDITOR';
export const MODE_COSTUME_ADDING = 'MODE_COSTUME_ADDING';
export const MODE_COSTUME_CERTIFY = 'MODE_COSTUME_CERTIFY';


export const DISPATCHER_SWITCH_COSTUME_OWNER = 'DISPATCHER_SWITCH_COSTUME_OWNER';
export const DISPATCHER_FLUSH_COSTUME_OWNER = 'DISPATCHER_FLUSH_COSTUME_OWNER';
export const DISPATCHER_COSTUME_WASH_INSIDE = 'DISPATCHER_COSTUME_WASH_INSIDE';
export const DISPATCHER_SWITCH_COSTUME_SIZE = 'DISPATCHER_SWITCH_COSTUME_SIZE';
export const DISPATCHER_SWITCH_COSTUME_LOCATION = 'DISPATCHER_SWITCH_COSTUME_LOCATION';
export const DISPATCHER_SWITCH_COSTUME_COMPOSITION = 'DISPATCHER_SWITCH_COSTUME_COMPOSITION';
export const DISPATCHER_COSTUME_DISINFECT = 'DISPATCHER_COSTUME_DISINFECT';
export const DISPATCHER_COSTUME_REPAIR = 'DISPATCHER_COSTUME_REPAIR';
export const DISPATCHER_COSTUME_CERTIFICATION = 'DISPATCHER_COSTUME_CERTIFICATION';

export const DISPATCHER_COSTUME_ADD = 'DISPATCHER_COSTUME_ADD';