export const MODE_INITIAL_TABLE_VIEW = 'MODE_INITIAL_TABLE_VIEW';
export const MODE_COSTUME_EDITOR = 'MODE_COSTUME_EDITOR';
export const MODE_COSTUME_ADDING = 'MODE_COSTUME_ADDING';


export const DISPATCHER_SWITCH_COSTUME_OWNER = 'DISPATCHER_SWITCH_COSTUME_OWNER';
export const DISPATCHER_FLUSH_COSTUME_OWNER = 'DISPATCHER_FLUSH_COSTUME_OWNER';

export const DISPATCHER_COSTUME_ADD = 'DISPATCHER_COSTUME_ADD';